---
title: "Intro to DA - Lab 1"
author: "Abu Bakar Naseer"
date: "Saturday, 5th of Oct' 2019"
output: html_document
---

[//]:(lalal lal alk)

# Q1
```{r}
u=seq(-10,0)
u=-10:0
u
```


# Q2
```{r}
v=seq(-0.1,by=0.5,length=11)
v=seq(-0.1,4.9,length=11)
v
```


# Q3
```{r}
u+v
u*v
```


# Q4
```{r}
u=u+1
v=0.8*v
```


# Q5
```{r}
w=c(u,v)
w

len=length(w)
len
```



# Q6
```{r}
w[14:16]
w[c(2,5,9)]
w[23]
```

# Q7
```{r}
w[3]=100
w[c(7,15,22)]=c(200,300,400)
w
```

# Q8
```{r}
rm(u)
```


# Q9
```{r}
rm(list=ls())
```

# Q10
```{r}
help("exp")

exp(1)
cos(90)

p=seq(3,6,by=0.1)
p=exp(p)*cos(p)
p

p1=exp(seq(3,6,by=0.1))*cos(seq(3,6,by=0.1))
p1
```


# Q11
```{r}
max(p)
p
which(p==max(p))
which(p==min(p))
```


# Q12
```{r}
sort(p, decreasing=TRUE)
```


# Q13
```{r}
rep(c(4,6,3),10)
length(which(rep(c(4,6,3),10)==4))
```


# Q14
```{r}
c(rep(4,10),rep(6,20),rep(3,30))
```

## Matrices
# Q1
```{r}
b_matrix=matrix(
  seq(1,39,by=2),
  4,
  5,
  byrow=TRUE,
  dimnames = list(
                  c("A","B","C","D"),
                  c("a","b","c","d","e")
                  )
   )

b_matrix
```

# Q2
```{r}
subB=b_matrix[c("A","B","D"),c("b","c")]
b_matrix[-3,-c(1,4,5)]
```


# Q3
```{r}
a_matrix=matrix(
  1:12,
  4,
  3,
  dimnames=
    list(
      c("one","two","three","four"),
      c("eins","zwei","drei")
    )
)
a_matrix
```

# Q3
a_matrix %*% b_matrix #ERROR

```{r}
a_matrix %*% subB
```


# Q4
```{r}
x=1:3
y=4:6
z=7:9
rbind(a=(cbind(x,y,z))[1,], b=(cbind(x,y,z))[2,],c=(cbind(x,y,z))[3,])
```
